Building DAG of jobs...
shared_storage_local_copies: True
remote_exec: False
Retrieving input from storage.
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job            count
-----------  -------
process_yml        1
total              1

Resources before job selection: {'_cores': 1, '_nodes': 9223372036854775807}
Ready jobs (1)
Select jobs to execute...
Selected jobs (1)
Resources after job selection: {'_cores': 0, '_nodes': 9223372036854775806}
Execute 1 jobs...

[Wed May  1 18:00:52 2024]
localrule process_yml:
    input: F:/Lightsheet Workflows/analysis/Olivier_Burri/AB001/AB001_configuration.yml
    output: done.txt
    jobid: 0
    reason: Missing output files: done.txt
    resources: tmpdir=C:\Users\oburri\AppData\Local\Temp


		type nul > "F:/Lightsheet Workflows/analysis/Olivier_Burri/AB001/AB001_configuration.yml.xml"
		
Full Traceback (most recent call last):
  File "D:\conda\conda-envs\snakemake\Lib\site-packages\snakemake\executors\local.py", line 420, in run_wrapper
    run(
  File "F:\Lightsheet Workflows\lightsheet-brain-workflows\snakemake\Snakefile", line 25, in __rule_process_yml
  File "D:\conda\conda-envs\snakemake\Lib\site-packages\snakemake\shell.py", line 297, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'type nul > "F:/Lightsheet Workflows/analysis/Olivier_Burri/AB001/AB001_configuration.yml.xml"' returned non-zero exit status 1.

Full Traceback (most recent call last):
  File "D:\conda\conda-envs\snakemake\Lib\site-packages\snakemake\executors\local.py", line 420, in run_wrapper
    run(
  File "F:\Lightsheet Workflows\lightsheet-brain-workflows\snakemake\Snakefile", line 25, in __rule_process_yml
  File "D:\conda\conda-envs\snakemake\Lib\site-packages\snakemake\shell.py", line 297, in __new__
    raise sp.CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'type nul > "F:/Lightsheet Workflows/analysis/Olivier_Burri/AB001/AB001_configuration.yml.xml"' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\conda\conda-envs\snakemake\Lib\site-packages\snakemake\executors\local.py", line 259, in _callback
    raise ex
  File "D:\conda\conda-envs\snakemake\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\conda\conda-envs\snakemake\Lib\site-packages\snakemake\executors\local.py", line 245, in cached_or_run
    run_func(*args)
  File "D:\conda\conda-envs\snakemake\Lib\site-packages\snakemake\executors\local.py", line 456, in run_wrapper
    raise RuleException(
snakemake.exceptions.RuleException: CalledProcessError in file F:\Lightsheet Workflows\lightsheet-brain-workflows\snakemake\Snakefile, line 13:
Command 'type nul > "F:/Lightsheet Workflows/analysis/Olivier_Burri/AB001/AB001_configuration.yml.xml"' returned non-zero exit status 1.

RuleException:
CalledProcessError in file F:\Lightsheet Workflows\lightsheet-brain-workflows\snakemake\Snakefile, line 13:
Command 'type nul > "F:/Lightsheet Workflows/analysis/Olivier_Burri/AB001/AB001_configuration.yml.xml"' returned non-zero exit status 1.
[Wed May  1 18:00:52 2024]
Error in rule process_yml:
    jobid: 0
    input: F:/Lightsheet Workflows/analysis/Olivier_Burri/AB001/AB001_configuration.yml
    output: done.txt
    shell:
        
		type nul > "F:/Lightsheet Workflows/analysis/Olivier_Burri/AB001/AB001_configuration.yml.xml"
		
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake\log\2024-05-01T180052.619678.snakemake.log
unlocking
removing lock
removing lock
removed all locks
Full Traceback (most recent call last):
  File "D:\conda\conda-envs\snakemake\Lib\site-packages\snakemake\cli.py", line 1963, in args_to_api
    dag_api.execute_workflow(
  File "D:\conda\conda-envs\snakemake\Lib\site-packages\snakemake\api.py", line 568, in execute_workflow
    workflow.execute(
  File "D:\conda\conda-envs\snakemake\Lib\site-packages\snakemake\workflow.py", line 1256, in execute
    raise WorkflowError("At least one job did not complete successfully.")
snakemake_interface_common.exceptions.WorkflowError: At least one job did not complete successfully.

WorkflowError:
At least one job did not complete successfully.
